.PHONY: part1 part2 part3 part4
FLAGS=-U postgres -d labs_db -q

all: part1 part2 part3 part4

part1:
	psql -c '\i $@.sql' $(FLAGS)

part2:
	psql -c '\i $@.sql' $(FLAGS)

part3:
	psql -c '\i $@.sql' $(FLAGS)

part4:
	psql -c '\i $@.sql' $(FLAGS)